CREATE TABLE schedule(
	id INT AUTO_INCREMENT NOT NULL,
	title VARCHAR(35) NOT NULL,
	sdate VARCHAR(20) NOT NULL,
	stime VARCHAR(20) NOT NULL,
	sat TINYINT NOT NULL DEFAULT 0,
	sun TINYINT NOT NULL DEFAULT 0,
	mon TINYINT NOT NULL DEFAULT 0,
	tue TINYINT NOT NULL DEFAULT 0,
	wed TINYINT NOT NULL DEFAULT 0,
	thu TINYINT NOT NULL DEFAULT 0,
	fri TINYINT NOT NULL DEFAULT 0,
	PRIMARY KEY (id)
);